In [1]:
import numpy as np 
np.zeros((2, 3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [2]:
randomArray = np.random.random((2, 3))
randomArray


array([[ 0.30511677,  0.10802618,  0.70744868],
       [ 0.10501039,  0.42744627,  0.23299733]])

In [3]:
randomArray[1][2]

0.23299733432055503

In [4]:
randomArray[1,2] #d调用方法挺有意思。行列都在同一个中括号内

0.23299733432055503

In [5]:
randomArray.reshape((3, 2))

array([[ 0.30511677,  0.10802618],
       [ 0.70744868,  0.10501039],
       [ 0.42744627,  0.23299733]])

In [6]:
squareArray = np.arange(1, 10).reshape((3, 3))

In [7]:
squareArray[0, 0:2] #第一行，0,1列。 

array([1, 2])

In [8]:
randomRow = np.random.random((10, 1))
fibIndices = np.array([1, 1, 2, 3])
randomRow[fibIndices] #用数组作为调用的值

array([[ 0.56033178],
       [ 0.56033178],
       [ 0.29269465],
       [ 0.75065887]])

In [9]:
boolIndices = np.array([[True, False, True], [False, True, False], [True, False, True]]) #多维数组，中括号套中括号
squareArray[boolIndices] #仅仅调用true的

array([1, 3, 5, 7, 9])

In [10]:
np.median(squareArray)

5.0

In [11]:
np.sum(squareArray)

45

In [12]:
np.sum(squareArray[:, 0])

12

In [17]:
betterAverage = squareArray > np.average(squareArray) #哪些大于均值，返回布尔值
betterAverage #本身是一个有是、否组成的数组。用来调用相应位置的数值。

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]], dtype=bool)

In [15]:
squareArray[betterAverage] # 选出大于均值的数字。对使用矩阵作为调用符合某些条件的index的一个范例

array([6, 7, 8, 9])

1、np的各种命令array, arange(array range的缩写)，zeros, ones，random产生的对象都是array属性
2、array可以reshape
3、array的数据提供是list，其内部元素也是list，所以就是中括号套中括号
4、array的调用可以是一个list，每个元素表示第几个位置；或者[0:n, 0:n ],横纵坐标都在一个中括号内，当然两个中括号也很好用；或者同形态结构的数组作为下标来调用，例如同形态的True, Flase；或者是一个条件等式，例如数组大于某个值，返回数组形态的true, false。
5、pandas的dataframa主要是处理时间序列；numpy主要进行数字计算，使用c语言编写，运行速度快。



In [22]:
sqAverage = np.average(squareArray)
sqStdDev = np.std(squareArray)
clampedSqArray = np.array(squareArray.copy(), dtype=float) 
                                    # make a copy of squareArray that will
                                    # be "clamped". It will only contain
                                    # values within one standard deviation
                                    # of the mean. Values that are too low
                                    # or to high will be set to the min
                                    # and max respectively. We set 
                                    # dtype=float because sqAverage
                                    # and sqStdDev are floating point
                                    # numbers, and we don't want to 
                                    # truncate them down to integers.
clampedSqArray[ (squareArray-sqAverage) > sqStdDev ] = sqAverage+sqStdDev #直接用等式计算一个true、false矩阵作为index调用所谓数组元素，然后赋值。

In [16]:
print squareArray * 2 # [[ 2  4  6] 除非用点程，否则矩阵都是简单的一一对应四则运算。
                      #  [ 8  0 12]
                      #  [ 2  2  2]]

## Addition works similarly:
print squareArray + np.ones( (3,3) ) #[[2 3 4]
                                     # [5 1 7]
                                     # [2 2 2]]

## Multiplying two arrays together (of the same size) is also element wise
print squareArray * np.arange(1,10).reshape( (3,3) ) #[[ 1  4  9]
                                                     # [16  0 36]
                                                     # [ 7  8  9]]

## Unless you use the dot(...) function, which does matrix multiplication
## from linear algebra:
matA = np.array( [[1,2],[3,4]] )
matB = np.array( [[5,6],[7,8]] )
print np.dot(matA,matB) #[[19 22] 此处才是矩阵的点乘
                        # [43 50]]

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[  2.   3.   4.]
 [  5.   6.   7.]
 [  8.   9.  10.]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
[[19 22]
 [43 50]]


In [19]:
fred = squareArray.copy() #这样，改变fred不会改变squareArray